### ISSUE TITLE
Change scan name

### ISSUE THREAD

**Issue by Johnthe0n** [T0pCyber/hawk#104] opened 2023-05-08 13:49 UTC
I have uninstalled and reinstalled the Hawk PS module and the scan is still showing with the same scan name from the previous install, is there a way to resolve this? 
Thank you

**Comment by clj575** [comment] 2023-05-17 22:12
I can confirm this issue. This has been happening since the last update. The tenant would update when creating a new scan. Now it stays the same on every new client.

**Comment by T0pCyber** [comment] 2023-05-18 10:09
We're taking a look. Appreciate letting us know.

**Comment by MSFT-SeanG** [comment] 2023-05-18 11:52
@Johnthe0n & @clj575 

Which cmdlet are you calling that this is presenting the issue - User or Tenant investigations?

**Comment by MackT4** [comment] 2023-05-18 13:17
@MSFT-SeanG I am seeing the same issue when using the **Start-HawkTenantInvestigation** cmdlet

**Comment by Johnthe0n** [comment] 2024-04-23 13:16
Sorry, I have not logged in here in FOREVER. Its a new session I am running each time and I have uninstalled and reinstalled the HAWK system from PowerShell, that did not work. I am saving the sessions to different folders each time I run scans.

**Comment by jonnybottles** [comment] 2024-11-27 17:50
Closing this ticket out as it appears to be the same issue identified in ticket https://github.com/T0pCyber/hawk/issues/106. Adding the original issue description to the comments of ticket 106.

**Closed by jonnybottles** 2024-11-27 17:50 UTC
Labels: type/question
