### ISSUE TITLE
New Tenant Investigations going into wrong tenant folder

### ISSUE THREAD

**Issue by CTI-Corey** [T0pCyber/hawk#118] opened 2024-02-15 21:13 UTC
**Describe the bug**
Run different tenant investigations and they go into a folder with the name of the first tenant we investigated. 

**To Reproduce**
Run Start-HawkTenantInvestigation
Let it collect data.
Run another investigation (diff tenant) and it creates a new folder w/ the old tenants name.

**Expected behavior**
The new folder should have the name of the new tenant.

**Screenshots**
Not sharing screenshot due to privacy concerns of the tenant names.

**Comment by big-bad-wolfe** [comment] 2024-02-23 00:59
This is the same issue as #106 

Easiest way to get around it is run 

`Disconnect-MgGraph`

after you have completed the tenant investigation

**Comment by jonnybottles** [comment] 2024-11-27 13:53
Closing this ticket out as it is a duplicate of ticket 106. Adding the original issue description to the comments of ticket 106.

**Comment by jonnybottles** [comment] 2024-11-27 13:53
Closing this ticket out as it is a duplicate of ticket 106. Adding the original issue description to the comments of ticket 106.

**Closed** 2024-11-27 13:53 UTC
Labels: type/bug
